version: 0.1

phases:
  build:
    commands:
      - mvn cobertura:cobertura package
      - #!/bin/sh 
      - exec java -jar ~/bin/slave.jar
  
artifacts:
  files:
    - target/EmployeeApplication.war
    - target/*
  discard-paths: yes
